---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "camel-ose-springboot-xml"
  spec:
    tags:
    - from:
        kind: "ImageStreamImage"
        name: "camel-ose-springboot-xml@sha256:fd56409ca83f6b5d198d97bc4a3e41152e1d35ea940051f44e68307fefaae709"
        namespace: "amq"
      name: "latest"
