---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/git-commit: "cef586e0c5f08b431b05e8a0322d2c5e9354e461"
    fabric8.io/iconUrl: "img/icons/camel.svg"
    fabric8.io/git-branch: "master"
    fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=fis-demo&var-version=1.0.0-SNAPSHOT"
  labels:
    provider: "fabric8"
    project: "fis-demo"
    version: "1.0.0-SNAPSHOT"
    group: "org.mycompany"
  name: "fis-demo"
spec:
  replicas: 1
  selector:
    matchLabels:
      project: "fis-demo"
      provider: "fabric8"
      group: "org.mycompany"
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: "cef586e0c5f08b431b05e8a0322d2c5e9354e461"
        fabric8.io/iconUrl: "img/icons/camel.svg"
        fabric8.io/git-branch: "master"
        fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=fis-demo&var-version=1.0.0-SNAPSHOT"
      labels:
        provider: "fabric8"
        project: "fis-demo"
        version: "1.0.0-SNAPSHOT"
        group: "org.mycompany"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "mycompany/fis-demo:snapshot-171018-142824-0078"
        imagePullPolicy: "IfNotPresent"
        livenessProbe:
          httpGet:
            path: "/health"
            port: 8081
          initialDelaySeconds: 180
        name: "spring-boot"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        - containerPort: 9779
          name: "prometheus"
          protocol: "TCP"
        - containerPort: 8778
          name: "jolokia"
          protocol: "TCP"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8081
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: "1.0"
          requests:
            cpu: "0.2"
        securityContext:
          privileged: false
